// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css'; // Make sure this line exists and is correct

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the font class and potentially a class for overlay if you use it */}
      <body className={`${inter.className} relative`}>
        {/* If you use the overlay, add this div */}
        {/* <div className="background-overlay absolute inset-0 -z-10"></div> */}

        {children}
      </body>
    </html>
  );
}